// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIMS.DatabaseContext;

#nullable disable

namespace SIMS.Migrations
{
    [DbContext(typeof(SimDbContext))]
    [Migration("20251130064037_FinalSync")]
    partial class FinalSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("aspnetroles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetroleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuserroles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 2L,
                            RoleId = 2L
                        },
                        new
                        {
                            UserId = 5L,
                            RoleId = 3L
                        },
                        new
                        {
                            UserId = 6L,
                            RoleId = 3L
                        },
                        new
                        {
                            UserId = 9L,
                            RoleId = 3L
                        },
                        new
                        {
                            UserId = 12L,
                            RoleId = 1L
                        },
                        new
                        {
                            UserId = 16L,
                            RoleId = 1L
                        },
                        new
                        {
                            UserId = 17L,
                            RoleId = 4L
                        },
                        new
                        {
                            UserId = 18L,
                            RoleId = 4L
                        },
                        new
                        {
                            UserId = 19L,
                            RoleId = 4L
                        },
                        new
                        {
                            UserId = 20L,
                            RoleId = 4L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetusertokens", (string)null);
                });

            modelBuilder.Entity("SIMS.DatabaseContext.Entities.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("aspnetusers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1f20f25a-baf3-459e-a596-9c161caaa33c",
                            Email = "t1@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "T1@MAIL.COM",
                            NormalizedUserName = "TEACHER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db5d9651-83f8-4c05-bcd7-87bb4ed261be",
                            TwoFactorEnabled = false,
                            UserName = "teacher1"
                        },
                        new
                        {
                            Id = 5L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8291f5d-ded7-416e-9c53-445c0557735e",
                            Email = "s1@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "S1@MAIL.COM",
                            NormalizedUserName = "STUDENT1",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3e25fb21-b55c-4f0a-b738-15a8ea0a337a",
                            TwoFactorEnabled = false,
                            UserName = "student1"
                        },
                        new
                        {
                            Id = 6L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7737efd8-3a21-4013-afec-3b24a0e908f2",
                            Email = "s2@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "S2@MAIL.COM",
                            NormalizedUserName = "STUDENT2",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "be3f6a2d-96cc-4016-9acd-ec4a2778a36d",
                            TwoFactorEnabled = false,
                            UserName = "student2"
                        },
                        new
                        {
                            Id = 9L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aaa62926-e652-474b-804a-953d232f2b1e",
                            Email = "s5@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "S5@MAIL.COM",
                            NormalizedUserName = "STUDENT5",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4902137b-704b-42b8-a731-0d7966465886",
                            TwoFactorEnabled = false,
                            UserName = "student5"
                        },
                        new
                        {
                            Id = 12L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf929322-8635-4901-83ff-c2c3411f0a07",
                            Email = "sysadmin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SYSADMIN@EXAMPLE.COM",
                            NormalizedUserName = "SYSADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91bdeddf-9518-44e0-9a3a-26add81ba47b",
                            TwoFactorEnabled = false,
                            UserName = "sysadmin"
                        },
                        new
                        {
                            Id = 16L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9e92648a-1145-4eae-bd99-140d50252534",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "17b0f00a-647d-47ed-975b-f743e4f365d0",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 17L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4938aa81-5b3d-4916-941c-6970c8d29bc0",
                            Email = "dotrang2004mc@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DOTRANG2004MC@GMAIL.COM",
                            NormalizedUserName = "ABC",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "476c3a2b-7831-45a1-b6b6-73781dce6013",
                            TwoFactorEnabled = false,
                            UserName = "abc"
                        },
                        new
                        {
                            Id = 18L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1d016fc-4d53-4c80-94b5-0c550f4c1527",
                            Email = "ducd53776@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DUCD53776@GMAIL.COM",
                            NormalizedUserName = "DUCDM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9503ffc3-8df5-4e24-808d-9c6ba3802000",
                            TwoFactorEnabled = false,
                            UserName = "ducdm"
                        },
                        new
                        {
                            Id = 19L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f2c7595-871b-44c9-9657-7298d34bcccc",
                            Email = "mu@gamil.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MU@GAMIL.COM",
                            NormalizedUserName = "DOAN",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "41667a3d-8738-4434-ae0f-6669bfcaa1e0",
                            TwoFactorEnabled = false,
                            UserName = "doan"
                        },
                        new
                        {
                            Id = 20L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7f06751-9283-4bac-96d8-299cfb7ecdd4",
                            Email = "duc6@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DUC6@GMAIL.COM",
                            NormalizedUserName = "DOANMINHDUC",
                            PasswordHash = "AQAAAAIAAYagAAAAEAkcR5/UfOiMP3Zt5FIu+C2qfhPnJinFDx9h50baXnEq2yDMmaxI4y2FkekJIErocQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47afb4fc-cc99-4770-b720-cd69c441cb57",
                            TwoFactorEnabled = false,
                            UserName = "doanminhduc"
                        });
                });

            modelBuilder.Entity("SIMS.DatabaseContext.Entities.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("SIMS.DatabaseContext.Entities.Teacher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("SIMS.DatabaseContext.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("SIMS.DatabaseContext.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIMS.DatabaseContext.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("SIMS.DatabaseContext.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
